import { expect, test } from '@playwright/test'

test('empty app → trip → day → item → edit → reload → remove → undo', async ({ page }) => {
  await page.goto('/')
  await expect(page).toHaveTitle('Loom · Your personal travel planner')
  await expect(page.getByRole('link', { name: 'Loom home', exact: true })).toBeVisible()
  await expect(page.locator('link[rel="icon"]')).toHaveAttribute('href', /loom\.svg$/)
  await expect(page.getByText('Plan your next trip here.')).toBeVisible()
  await page.screenshot({ path: `test-results/${test.info().project.name}-empty-light.png` })
  await page.getByRole('button', { name: 'Create a trip', exact: true }).click()
  await page.getByLabel('Trip name').fill('Korea & Japan')
  await page.getByLabel('Start date').fill('2028-02-28')
  await page.getByLabel('End date').fill('2028-03-04')
  await page.getByRole('button', { name: 'Create trip', exact: true }).click()
  await page.getByRole('button', { name: 'Edit trip', exact: true }).click()
  await page.getByLabel('Trip name').fill('Korea & Japan · Spring')
  await page.getByRole('button', { name: 'Save trip', exact: true }).click()
  await page.getByRole('navigation').getByRole('button', { name: 'Days', exact: true }).click()
  expect((await page.getByLabel('Selected trip').boundingBox())?.height).toBeGreaterThanOrEqual(44)
  await page.getByRole('button', { name: 'Create your first day' }).click()
  await page.getByLabel('Date', { exact: true }).fill('2028-02-29')
  await page.getByLabel('City', { exact: true }).fill('서울')
  await page.getByLabel('Day title (optional)').fill('A day in Seoul')
  await page.getByRole('button', { name: 'Save day', exact: true }).click()
  await expect(page.getByText('Feb 29, 2028', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Add the first item' }).click()
  await page.getByRole('button', { name: 'Restaurant A table worth saving' }).click()
  await page.getByLabel('Restaurant name').fill('저녁 🍜')
  await page.getByLabel('Local time (optional)').fill('19:30')
  await page.getByLabel('Notes (optional)').fill('Book the counter seat if it is available.\nBring the neighborhood map.')
  await page.getByLabel('Instagram link (optional)').fill('https://www.instagram.com/example/')
  await page.getByLabel('Place name').fill('Gwangjang Market')
  await page.getByLabel('Place address').fill('88 Changgyeonggung-ro, Jongno-gu, Seoul')
  await page.getByLabel('Latitude').fill('37.5702')
  await page.getByLabel('Longitude').fill('126.9997')
  await page.getByLabel('Country').fill('South Korea')
  await page.locator('input[name="photos"]').setInputFiles({
    name: 'market.png', mimeType: 'image/png',
    buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=', 'base64'),
  })
  await page.getByLabel('Booking status').selectOption('booked')
  await page.getByLabel('Reference (optional)').fill('SEOUL-123')
  await page.getByLabel('Website or confirmation link (optional)').fill('javascript:alert(1)')
  await page.getByRole('button', { name: 'Add item', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('http:// or https://')
  await page.getByLabel('Website or confirmation link (optional)').fill('https://example.com/confirmation')
  await page.getByRole('button', { name: 'Add item', exact: true }).click()
  await page.getByRole('button', { name: /저녁 🍜/ }).click()
  await expect(page.getByText('SEOUL-123', { exact: true })).toBeVisible()
  await expect(page.getByText('Gwangjang Market', { exact: true })).toBeVisible()
  await expect(page.getByText('Book the counter seat if it is available.')).toBeVisible()
  await expect(page.getByText('1 photo', { exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Open Instagram' })).toHaveAttribute('href', 'https://www.instagram.com/example/')
  await expect(page.getByRole('link', { name: 'Open website or confirmation' })).toHaveAttribute('rel', 'noopener noreferrer')
  await page.getByRole('button', { name: 'Edit item', exact: true }).click()
  await page.getByLabel('Restaurant name').fill('Seoul dinner')
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await page.getByRole('button', { name: 'Close dialog' }).click()
  await expect(page.getByRole('button', { name: 'Explain local save status' })).toContainText('Saved')
  await page.reload()
  await expect(page.getByRole('button', { name: /Seoul dinner/ })).toBeVisible()
  await page.getByRole('navigation').getByRole('button', { name: 'Items', exact: true }).click()
  await page.getByRole('button', { name: /Seoul dinner/ }).click()
  await page.getByRole('button', { name: 'Remove', exact: true }).click()
  await expect(page.getByRole('button', { name: /Restaurant.*Seoul dinner/ })).toHaveCount(0)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(page.getByRole('button', { name: /Seoul dinner/ })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Explain local save status' })).toContainText('Saved')
  await page.reload()
  await expect(page.getByRole('button', { name: /Seoul dinner/ })).toBeVisible()
  await page.getByRole('navigation').getByRole('button', { name: 'Home', exact: true }).click()
  await page.getByLabel('Search trips, places, and bookings').fill('SEOUL-123')
  await expect(page.getByRole('button', { name: /Seoul dinner/ })).toBeVisible()
  await page.getByRole('navigation').getByRole('button', { name: 'Add', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'First, choose a trip.' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('navigation').getByRole('button', { name: 'Days', exact: true }).click()
  await page.screenshot({ path: `test-results/${test.info().project.name}-days.png`, fullPage: true })
})

test('profile, appearances, trip isolation, hash reload and 320px layout', async ({ page }) => {
  await page.goto('/#profile')
  await page.getByLabel('Display name').fill('Ada')
  await page.getByLabel('Appearance').selectOption('dark')
  await page.getByRole('button', { name: 'Save profile' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-appearance', 'dark')
  await page.getByRole('navigation').getByRole('button', { name: 'Home', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Hello, Ada.' })).toBeVisible()
  await page.screenshot({ path: `test-results/${test.info().project.name}-empty-dark.png`, fullPage: true })
  for (const name of ['First trip with a very long name that should wrap correctly in a square card', 'Second trip']) {
    await page.getByRole('button', { name: /Create a trip|New trip/, exact: true }).click()
    await page.getByLabel('Trip name').fill(name)
    await page.getByLabel('Start date').fill('2032-12-30')
    await page.getByLabel('End date').fill('2033-01-04')
    await page.getByRole('button', { name: 'Create trip', exact: true }).click()
  }
  await page.getByRole('navigation').getByRole('button', { name: 'Days', exact: true }).click()
  await expect(page.getByLabel('Selected trip').locator('option:checked')).toHaveText('Second trip')
  await page.getByRole('button', { name: 'Create your first day' }).click()
  await page.getByLabel('City', { exact: true }).fill('Tokyo')
  await page.getByRole('button', { name: 'Save day', exact: true }).click()
  await page.getByLabel('Selected trip').selectOption({ index: 0 })
  await expect(page.getByText('Make room for a day.')).toBeVisible()
  await page.reload()
  await expect(page.getByText('Make room for a day.')).toBeVisible()
  await page.setViewportSize({ width: 320, height: 720 })
  for (const name of ['Home', 'Days', 'Add', 'Items', 'Profile']) {
    await page.getByRole('navigation').getByRole('button', { name, exact: true }).click()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  }
  await page.getByLabel('Appearance').selectOption('light')
  await page.getByRole('button', { name: 'Save profile' }).click()
  await page.getByRole('navigation').getByRole('button', { name: 'Home', exact: true }).click()
  await page.screenshot({ path: `test-results/${test.info().project.name}-home-320.png`, fullPage: true })
})

test('edit day and delete trips with explicit confirmation', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Create a trip', exact: true }).click()
  await page.getByLabel('Trip name').fill('Trip to keep')
  await page.getByLabel('Start date').fill('2028-05-01')
  await page.getByLabel('End date').fill('2028-05-03')
  await page.getByRole('button', { name: 'Create trip', exact: true }).click()
  await page.getByRole('navigation').getByRole('button', { name: 'Days', exact: true }).click()
  await page.getByRole('button', { name: 'Create your first day' }).click()
  await page.getByLabel('City', { exact: true }).fill('Seoul')
  await page.getByLabel('Day title (optional)').fill('Original plan')
  await page.getByRole('button', { name: 'Save day', exact: true }).click()
  await page.getByRole('button', { name: 'Edit day', exact: true }).click()
  await page.getByLabel('City', { exact: true }).fill('Busan')
  await page.getByLabel('Day title (optional)').fill('Updated plan')
  await page.getByLabel('Notes (optional)').fill('Keep the afternoon open.')
  await page.getByRole('button', { name: 'Save day changes', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Updated plan' })).toBeVisible()
  await expect(page.getByRole('paragraph').filter({ hasText: 'Busan' })).toBeVisible()

  await page.getByRole('navigation').getByRole('button', { name: 'Home', exact: true }).click()
  await page.getByRole('button', { name: 'New trip', exact: true }).click()
  await page.getByLabel('Trip name').fill('Trip to delete')
  await page.getByLabel('Start date').fill('2028-06-01')
  await page.getByLabel('End date').fill('2028-06-03')
  await page.getByRole('button', { name: 'Create trip', exact: true }).click()
  await page.getByRole('button', { name: 'Edit trip', exact: true }).click()
  await page.getByRole('button', { name: 'Delete trip', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Delete this trip?' })).toBeVisible()
  await expect(page.getByRole('dialog', { name: 'Delete this trip?' }).getByText('Trip to delete', { exact: true })).toBeVisible()
  await page.getByRole('dialog', { name: 'Delete this trip?' }).getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Edit trip' })).toBeVisible()
  await page.getByRole('button', { name: 'Delete trip', exact: true }).click()
  await page.getByRole('button', { name: 'Delete trip permanently', exact: true }).click()
  await expect(page.getByText('Trip to delete', { exact: true })).toHaveCount(0)
  await expect(page.getByText('Trip to keep', { exact: true }).first()).toBeVisible()
  await page.reload()
  await expect(page.getByText('Trip to delete', { exact: true })).toHaveCount(0)
  await expect(page.getByText('Trip to keep', { exact: true }).first()).toBeVisible()

  await page.getByRole('button', { name: 'Edit trip', exact: true }).click()
  await page.getByRole('button', { name: 'Delete trip', exact: true }).click()
  await page.getByRole('button', { name: 'Delete trip permanently', exact: true }).click()
  await expect(page.getByText('Plan your next trip here.')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Explain local save status' })).toContainText('Saved')
  await page.reload()
  await expect(page.getByText('Plan your next trip here.')).toBeVisible()
})
